### ISSUE TITLE
L1/L2 Cache

### ISSUE THREAD

**Issue by KelvinYang0320** [pku-liang/TENET#5]
Does TENET support L1 and L2 cache size? 
MAESTRO returns warning messages for invalid cache sizes. I set the cache sizes for TENET to different values, but the result is still the same even if I set it to -1. 

To reproduce this problem, you could change L1/L2 cache size in   ./dataflow_example/pe_array.p  to -1, rerun the command, and compare the results with the original output.
Command from the [tutorial](https://pku-ahs.github.io/tutorial/en/master/_downloads/e59ee2860b8ed959a68a0c3f8b4ab308/tenet.pdf):
```script
bin/tenet --m ./dataflow_example/KC_systolic_dataflow.m --p ./dataflow_example/pe_array.p --s ./dataflow_example/conv.s --o test.csv --all

```
Could you provide a feature for detecting invalid cache sizes?

**Comment by wangyuyue** [comment]
Hi Kelvin,
Current open-sourced TENET doesn't have real support for memory hierarchy. Similar to MAESTRO, it assumes all tensors are completely loaded onto on-chip SRAM before the kernel launches, and it only models the procedure after the kernel launch.

Using a similar polyhedral model technique, I wrote some addition for TENET to support modeling on-chip scratchpad with a constraint data mapping. I will upload it to this repo this week and update this issue.

**Comment by KelvinYang0320** [comment]
> Using a similar polyhedral model technique, I wrote some addition for TENET to support modeling on-chip scratchpad with a constraint data mapping. I will upload it to this repo this week and update this issue.

@wangyuyue Thank you! That's great.

**Comment by wangyuyue** [comment]
Hi Kelvin,

I just uploaded the cache code into a new branch `cache`. The project structure changed since I introduced cache codes. I moved `cache.cpp` and `cache.h` to `/src` and `/include` folder respectively. You can use `test_cache.cpp` in `/test` to run cache-aware experiments. You may need to modify `Makefile` by yourself.

I also uploaded `operator.cpp` and `operator.h` to construct common operators. It should be helpful as a wrapper.

Please consider making a pull request to refine or extend them if you find them useful.

Thanks for your patience.
